# Debug settings
[debug]
streaming = true

# App layout
[layout]
show_3d_scene = true
title = "Connect"
logo_path = "assets/logo.png"

# Right panel configuration
[layout.right_panel]
enabled = true
default_width = 0.5  # Fraction of window width

[[layout.right_panel.tabs]]
id = "controls"
label = "Controls"

# Define available tabs
[[layout.right_panel.tabs]]
id = "docs"
label = "Instructions"

# Documentation configuration
[layout.docs]
path = "instructions.md"
tab = "docs"  # Assign to first tab

# Plot configuration
[layout.plot]
type = "line"
title = "Streaming Data Plot"
x_label = "Time (s)"
y_label = "Value"
tab = "controls"  # Assign to second tab

# Input fields configuration
[[layout.input_fields]]
id = "filter"
label = "Filter Expression"
tab = "controls"  # Assign to second tab

[[layout.input_fields]]
id = "threshold"
label = "Threshold Value"
tab = "controls"  # Assign to second tab

# Slider configuration
[[layout.sliders]]
id = "frequency"
label = "Frequency"
min = 0.0
max = 10.0
default = 1.0
tab = "controls"  # Assign to second tab

[[layout.sliders]]
id = "y_axis_offset"
label = "Offset"
min = -5.0
max = 5.0
default = 0.0
tab = "controls"  # Assign to second tab

[[layout.input_fields]]
id = "csv_path"
label = "CSV File Path"
tab = "controls"

# Add a new tab for the table
[[layout.right_panel.tabs]]
id = "table_view"
label = "Table View"

# Table configuration
[layout.table]
tab = "table_view"  # Link to the tab where the table should appear
columns = [
    "ID",
    "Status",
    "Value",
    "Timestamp"
]
data = [
    ["001", "Active", "23.5", "2024-03-20 10:00"],
    ["002", "Inactive", "15.7", "2024-03-20 10:01"],
    ["003", "Active", "42.1", "2024-03-20 10:02"]
]

# Optional table styling (for future expansion)
[layout.table.style]
striped = true
borders = true
header_background = "#404040"
row_height = 30

# Python scripts

[[scripts]]
name = "Print random"
path = "rand.py"
type = "discrete"

[[scripts]]
name = "Sine Wave"
path = "stream_example.py"
type = "streaming"

[[scripts]]
name = "Echo inputs"
path = "echo.py"
type = "discrete"
functions = [
    { name = "echo_one", display = "Field 1" },
    { name = "echo_two", display = "Field 2" }
]

[[scripts]]
name = "Read CSV"
path = "read_csv.py"
type = "discrete"
