# Debug settings
[debug]
streaming = true

# App layout
[layout]
show_3d_scene = true
title = "Connect"
logo_path = "assets/logo.png"

# Right panel configuration
[layout.right_panel]
enabled = true
default_width = 0.5  # Fraction of window width

[[layout.right_panel.tabs]]
id = "controls"
label = "Controls"

# Define available tabs
[[layout.right_panel.tabs]]
id = "docs"
label = "Instructions"

# Documentation configuration
[layout.docs]
path = "instructions.md"
tab = "docs"  # Assign to first tab

# Plot configuration
[layout.plot]
type = "line"
title = "Streaming Data Plot"
x_label = "Time (s)"
y_label = "Value"
tab = "controls"  # Assign to second tab

# Input fields configuration
[[layout.input_fields]]
id = "filter"
label = "Filter Expression"
tab = "controls"  # Assign to second tab

[[layout.input_fields]]
id = "threshold"
label = "Threshold Value"
tab = "controls"  # Assign to second tab

# Slider configuration
[[layout.sliders]]
id = "frequency"
label = "Frequency"
min = 0.0
max = 10.0
default = 1.0
tab = "controls"  # Assign to second tab

[[layout.sliders]]
id = "y_axis_offset"
label = "Offset"
min = -5.0
max = 5.0
default = 0.0
tab = "controls"  # Assign to second tab

# Python scripts

[[scripts]]
name = "Print random"
path = "rand.py"
type = "discrete"

[[scripts]]
name = "Sine Wave"
path = "stream_example.py"
type = "streaming"

[[scripts]]
name = "Echo inputs"
path = "echo.py"
type = "discrete"
functions = [
    { name = "echo_one", display = "Field 1" },
    { name = "echo_two", display = "Field 2" }
]