# Debug settings
[debug]
streaming = true

# App layout
[layout]
show_3d_scene = true
title = "Connect"
logo_path = "assets/logo.png"

# Left panel configuration (new section)
[layout.left_panel]
enabled = true
default_width = 0.2 # Fraction of window width

[[layout.left_panel.tabs]]
id = "docs"
label = "Instructions"

# Right panel configuration
[layout.right_panel]
enabled = true
default_width = 0.2 # Fraction of window width

[[layout.right_panel.tabs]]
id = "controls"
label = "Controls"

# Plot configuration
[layout.plot]
type = "line"
title = "Streaming Data Plot"
x_label = "Time (s)"
y_label = "Value"
tab = "controls"              # Assign to second tab

# Python scripts

[[scripts]]
name = "Flight Replay"
path = "flight_replay.py"
type = "streaming"

[[scripts]]
name = "Fail Status"
path = "fail_status.py"
type = "streaming"
